name: viskepler
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - fastapi=0.100.0
  - uvicorn=0.32.0
  - pydantic=2.10.6
  - pydantic-settings=2.7.1
  - requests=2.32.3
  - numpy=2.1.2
  - pandas=2.2.3
  - geopandas=1.0.1
  - jinja2=3.1.4
  - itsdangerous=2.2.0
  - python-multipart=0.0.12
  - unidecode=1.3.8
  - weasyprint=62.3
  - plotly=5.24.1
  - pip
  - pip:
      - keplergl==0.3.2